name: Project building and testing

on:
  
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
    - master
    paths:
    - "src/**"

jobs:
  build:
    
    name: Building and testing
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        gradle: [6.5.1]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: false
    
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    
    - name: Build and test project
      uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: ${{ matrix.gradle }}
        build-root-directory: ./
        arguments: build
